import type { FlightDetail } from "./flightDetailsTypes";
import { normalizeFlightNumberKey } from "./flightDetail";

function ev(
  time: string,
  label: string,
  state: "completed" | "active" | "upcoming"
) {
  return { time, label, state };
}

const TK1234: FlightDetail = {
  flightNumber: "TK1234",
  airlineName: "Turkish Airlines",
  status: "In flight",
  statusTone: "green",
  departureAirportCode: "SAW",
  departureAirportName: "Sabiha Gökçen International",
  departureCity: "Istanbul",
  departureTime: "18:45",
  estimatedDepartureTime: "18:45",
  actualDepartureTime: "18:48",
  arrivalAirportCode: "DUS",
  arrivalAirportName: "Düsseldorf International",
  arrivalCity: "Düsseldorf",
  arrivalTime: "21:05",
  estimatedArrivalTime: "21:05",
  gate: "A12",
  terminal: "1",
  departureTerminal: "1",
  arrivalTerminal: "1",
  arrivalGate: "B22",
  aircraftType: "Airbus A321neo",
  tailNumber: "TC-LGR",
  aircraftAgeYears: 4.2,
  seatCount: 186,
  seatLayout: "3-3 (economy / business forward cabin)",
  registrationCountry: "Türkiye",
  progressPercent: 48,
  livePhase: "in_air",
  liveStatusPhrase: "Cruising at 36,000 ft",
  liveStatusLines: [
    "Boarding complete",
    "Departed 12 min ago",
    "Arriving in 1h 42m",
  ],
  routePhaseLabel: "In air",
  routeSublabel: "Landing in 18 min",
  estimatedArrivalCaption: "Estimated arrival in 1h 42m",
  badges: [
    { text: "On Time", variant: "success" },
    { text: "Departed 12 min ago", variant: "info" },
  ],
  stats: {
    distance: "1,247 nm",
    duration: "2h 20m",
    speed: "452 kts",
    altitude: "36,000 ft",
    destinationWeather: "Partly cloudy · 8°C · light winds",
  },
  timelineEvents: [
    ev("18:05", "Boarding started", "completed"),
    ev("18:20", "Gate opened", "completed"),
    ev("18:42", "Pushback", "completed"),
    ev("18:48", "Takeoff", "completed"),
    ev("18:48", "Departed runway", "completed"),
    ev("21:01", "Landing", "upcoming"),
    ev("21:08", "Arrived at gate", "upcoming"),
  ],
  history: [
    {
      flightNumber: "TK1587",
      from: "IST",
      to: "FRA",
      departureTime: "08:10",
      arrivalTime: "10:35",
      dayGroup: "today",
      status: "Landed",
      delayed: false,
      onTime: true,
    },
    {
      flightNumber: "TK1588",
      from: "FRA",
      to: "IST",
      departureTime: "11:20",
      arrivalTime: "14:05",
      dayGroup: "today",
      status: "Landed",
      delayed: false,
      onTime: true,
      turnaroundFromPrevMinutes: 45,
    },
    {
      flightNumber: "TK2210",
      from: "IST",
      to: "SAW",
      departureTime: "14:57",
      arrivalTime: "15:33",
      dayGroup: "today",
      status: "Landed",
      delayed: true,
      onTime: false,
      turnaroundFromPrevMinutes: 52,
    },
    {
      flightNumber: "TK1234",
      from: "SAW",
      to: "DUS",
      departureTime: "18:45",
      arrivalTime: "21:05",
      dayGroup: "today",
      status: "En route",
      delayed: false,
      isCurrent: true,
      turnaroundFromPrevMinutes: 192,
    },
    {
      flightNumber: "TK2401",
      from: "IST",
      to: "AYT",
      departureTime: "07:40",
      arrivalTime: "09:15",
      dayGroup: "yesterday",
      status: "Landed",
      delayed: false,
      onTime: true,
    },
    {
      flightNumber: "TK2402",
      from: "AYT",
      to: "IST",
      departureTime: "10:15",
      arrivalTime: "11:55",
      dayGroup: "yesterday",
      status: "Landed",
      delayed: false,
      onTime: true,
      turnaroundFromPrevMinutes: 65,
    },
    {
      flightNumber: "TK2180",
      from: "IST",
      to: "ESB",
      departureTime: "13:00",
      arrivalTime: "14:10",
      dayGroup: "yesterday",
      status: "Landed",
      delayed: true,
      onTime: false,
      turnaroundFromPrevMinutes: 70,
    },
  ],
  aircraftTailTracking: {
    currentLocationLine: "Currently cruising near Belgrade",
    turnaround: {
      narrativeLine:
        "Aircraft arrived at SAW from IST at 15:33 after the domestic shuttle.",
      groundTimeBeforeNextDeparture: "3h 12m",
      lateInboundMessage:
        "Late inbound aircraft from IST added pressure on turnaround — knock-on delay ~18 min vs schedule.",
    },
    usageStats: {
      flightsToday: 5,
      airportsVisitedToday: 4,
      totalFlightTimeToday: "9h 15m",
      longestRouteToday: "IST → FRA",
    },
    routeMapAirports: ["IST", "FRA", "IST", "SAW", "DUS"],
    activeRouteLegStartIndex: 3,
    previousFlight: {
      flightNumber: "TK2210",
      from: "IST",
      to: "SAW",
      landedAgo: "3h 12m ago",
    },
  },
  nextFlight: {
    flightNumber: "TK1235",
    from: "DUS",
    to: "IST",
    departureTime: "23:20",
  },
  delayRiskLevel: "medium",
  delayRiskFactors: [
    "Aircraft arrived only 32 min before departure (IST → SAW leg).",
    "Incoming aircraft delayed 18 min on previous segment.",
    "Weather in destination may affect arrival (moderate crosswinds forecast).",
    "Gate at destination not yet confirmed on airport feed.",
  ],
};

const LH2029: FlightDetail = {
  flightNumber: "LH2029",
  airlineName: "Lufthansa",
  status: "Boarding",
  statusTone: "green",
  departureAirportCode: "DUS",
  departureAirportName: "Düsseldorf International",
  departureCity: "Düsseldorf",
  departureTime: "14:20",
  estimatedDepartureTime: "14:20",
  arrivalAirportCode: "MUC",
  arrivalAirportName: "Munich Franz Josef Strauss",
  arrivalCity: "Munich",
  arrivalTime: "15:15",
  estimatedArrivalTime: "15:15",
  gate: "B44",
  terminal: "A",
  arrivalGate: "G12",
  aircraftType: "Airbus A320neo",
  tailNumber: "D-AINA",
  aircraftAgeYears: 3.1,
  seatCount: 180,
  seatLayout: "3-3",
  registrationCountry: "Germany",
  progressPercent: 12,
  livePhase: "boarding",
  liveStatusPhrase: "Boarding now — final call soon",
  liveStatusLines: ["Boarding", "Final call", "Taxiing to runway in ~12 min"],
  routePhaseLabel: "Boarding",
  routeSublabel: "Taxiing to runway in ~12 min",
  estimatedArrivalCaption: "Estimated arrival in 58m",
  badges: [
    { text: "On Time", variant: "success" },
    { text: "Boarding", variant: "info" },
    { text: "Final Call", variant: "warning" },
  ],
  stats: {
    distance: "298 nm",
    duration: "55m",
    speed: "—",
    altitude: "Ground",
    destinationWeather: "Clear · 4°C",
  },
  timelineEvents: [
    ev("13:50", "Boarding started", "active"),
    ev("14:05", "Gate opened", "upcoming"),
    ev("14:15", "Pushback", "upcoming"),
    ev("14:25", "Takeoff", "upcoming"),
    ev("15:10", "Landing", "upcoming"),
    ev("15:18", "Arrived at gate", "upcoming"),
  ],
  history: [
    {
      flightNumber: "LH2010",
      from: "FRA",
      to: "DUS",
      departureTime: "11:00",
      arrivalTime: "11:55",
      dayGroup: "today",
      status: "Landed",
      delayed: false,
      onTime: true,
    },
    {
      flightNumber: "LH2029",
      from: "DUS",
      to: "MUC",
      departureTime: "14:20",
      arrivalTime: "15:15",
      dayGroup: "today",
      status: "Boarding",
      delayed: false,
      isCurrent: true,
      turnaroundFromPrevMinutes: 145,
    },
  ],
  aircraftTailTracking: {
    currentLocationLine: "Currently at DUS gate B44",
    inboundWarning: {
      message:
        "Your aircraft is still arriving from another destination. Boarding may start once the jetway is secured.",
      estimatedReadiness: "1h 35m",
    },
    turnaround: {
      narrativeLine: "Aircraft arrived at DUS from FRA at 11:55.",
      groundTimeBeforeNextDeparture: "2h 25m",
    },
    previousFlight: {
      flightNumber: "LH2010",
      from: "FRA",
      to: "DUS",
      landedAgo: "2h 25m ago",
    },
    usageStats: {
      flightsToday: 2,
      airportsVisitedToday: 3,
      totalFlightTimeToday: "2h 40m",
      longestRouteToday: "FRA → DUS",
    },
    routeMapAirports: ["FRA", "DUS", "MUC"],
    activeRouteLegStartIndex: 1,
  },
  delayRiskLevel: "low",
  delayRiskFactors: [
    "Short turnaround; aircraft on stand with no reported delay.",
    "No significant weather on filed route.",
  ],
};

const PC2092: FlightDetail = {
  flightNumber: "PC2092",
  airlineName: "Pegasus Airlines",
  status: "Delayed",
  statusTone: "yellow",
  departureAirportCode: "SAW",
  departureAirportName: "Sabiha Gökçen International",
  departureCity: "Istanbul",
  departureTime: "09:30",
  estimatedDepartureTime: "09:52",
  arrivalAirportCode: "ADA",
  arrivalAirportName: "Adana Şakirpaşa",
  arrivalCity: "Adana",
  arrivalTime: "11:10",
  estimatedArrivalTime: "11:32",
  gate: "G7",
  terminal: "Main",
  departureTerminal: "Main",
  arrivalTerminal: "Domestic",
  aircraftType: "Boeing 737-800",
  tailNumber: "TC-RDP",
  aircraftAgeYears: 8.6,
  seatCount: 189,
  seatLayout: "3-3",
  registrationCountry: "Türkiye",
  progressPercent: 0,
  livePhase: "boarding",
  liveStatusPhrase: "Boarding — revised departure time",
  routePhaseLabel: "Delayed 22 min",
  routeSublabel: "Gate may change — check displays",
  estimatedArrivalCaption: "Estimated arrival in 2h 02m (revised)",
  badges: [
    { text: "Delayed 22m", variant: "warning" },
    { text: "Gate changed", variant: "danger" },
    { text: "Boarding", variant: "info" },
  ],
  stats: {
    distance: "478 nm",
    duration: "1h 40m (sched.)",
    speed: "—",
    altitude: "Ground",
    destinationWeather: "Haze · 14°C",
  },
  timelineEvents: [
    ev("09:00", "Boarding started", "completed"),
    ev("09:15", "Gate opened", "completed"),
    ev("09:28", "Pushback", "upcoming"),
    ev("09:52", "Takeoff (revised)", "active"),
    ev("11:25", "Landing (est.)", "upcoming"),
    ev("11:32", "Arrived at gate (est.)", "upcoming"),
  ],
  history: [
    {
      flightNumber: "PC2091",
      from: "ADA",
      to: "SAW",
      departureTime: "06:40",
      arrivalTime: "08:05",
      dayGroup: "today",
      status: "Landed",
      delayed: true,
      onTime: false,
    },
    {
      flightNumber: "PC2092",
      from: "SAW",
      to: "ADA",
      departureTime: "09:30",
      arrivalTime: "11:10",
      dayGroup: "today",
      status: "Delayed",
      delayed: true,
      onTime: false,
      isCurrent: true,
      turnaroundFromPrevMinutes: 85,
    },
  ],
  aircraftTailTracking: {
    currentLocationLine: "Currently at SAW gate G7",
    turnaround: {
      narrativeLine: "Aircraft arrived at SAW from ADA at 08:05.",
      groundTimeBeforeNextDeparture: "1h 25m",
      lateInboundMessage:
        "Late inbound aircraft from ADA delayed departure by 25 min.",
    },
    previousFlight: {
      flightNumber: "PC2091",
      from: "ADA",
      to: "SAW",
      landedAgo: "about 1h 25m ago",
    },
    usageStats: {
      flightsToday: 2,
      airportsVisitedToday: 2,
      totalFlightTimeToday: "3h 05m",
      longestRouteToday: "SAW → ADA",
    },
    routeMapAirports: ["ADA", "SAW", "ADA"],
    activeRouteLegStartIndex: 1,
  },
  delayRiskLevel: "high",
  delayRiskFactors: [
    "Previous rotation arrived 25 min late.",
    "Tight turnaround — less than 90 min on ground.",
    "Destination visibility may require extra spacing.",
    "Gate not assigned yet on airport FIDS.",
  ],
};

const MOCKS: Record<string, FlightDetail> = {
  TK1234,
  LH2029,
  PC2092,
};

export function getMockFlightDetail(flightNumber: string): FlightDetail {
  const key = normalizeFlightNumberKey(flightNumber);
  const hit = MOCKS[key];
  if (hit) return { ...hit };
  return { flightNumber: key };
}

export function isMockFlightRegistered(flightNumber: string): boolean {
  const key = normalizeFlightNumberKey(flightNumber);
  return Object.prototype.hasOwnProperty.call(MOCKS, key);
}
